module.exports = {
    preset: 'ts-jest',
    rootDir: '../src',
    collectCoverageFrom: ['<rootDir>/src/**/*.{js,jsx,ts,tsx, mjs}', '!**/node_modules/**'],
    setupFilesAfterEnv: ['<rootDir>/../config/setupTests.ts'],
    testEnvironment: 'jsdom',
    moduleNameMapper: {
        '^assets(.*)$': '<rootDir>/assets$1',
        '^__ajaxHandlers__(.*)$': '<rootDir>/__ajaxHandlers__$1',
        '^common(.*)$': '<rootDir>/common$1',
        '^components(.*)$': '<rootDir>/components$1',
        '^hooks(.*)$': '<rootDir>/hooks$1',
        '^data(.*)$': '<rootDir>/data$1',
        '^container(.*)$': '<rootDir>/container$1',
        '^utils(.*)$': '<rootDir>/utils$1',
        '\\.(svg)$': '<rootDir>/__mocks__/fileMock.js',
        '^__testHelpers__(.*)$': '<rootDir>/__testHelpers__$1',
    },
    testPathIgnorePatterns: [
        '/node_modules/',
        '__config__',
        '__helpers__',
        '__mocks__',
        '__testData__',
        '__testHelpers__',
        '__ajaxHandlers__',
        'build',
    ],
};
