module.exports = {
    preset: 'ts-jest',
    rootDir: '../src',
    collectCoverageFrom: ['<rootDir>/src/**/*.{js,jsx,ts,tsx, mjs}', '!**/node_modules/**'],
    setupFilesAfterEnv: ['<rootDir>/../config/setupTests.ts'],
    testEnvironment: 'jsdom',
    moduleNameMapper: {
        '^assets(.*)$': '<rootDir>/assets$1',
        '^components(.*)$': '<rootDir>/components$1',
        '^data(.*)$': '<rootDir>/data$1',
        '^utils(.*)$': '<rootDir>/utils$1',
        '^container(.*)$': '<rootDir>/container$1',
        '^__mocks__(.*)$': '<rootDir>/__mocks__$1',
        '\\.(svg)$': '<rootDir>/__mocks__/fileMock.js',
        '^__testHelpers__(.*)$': '<rootDir>/__testHelpers__$1',
    },
    testPathIgnorePatterns: [
        '/node_modules/',
        '__config__',
        '__helpers__',
        '__mocks__',
        '__testData__',
        '__testHelpers__',
        'build',
    ],
};
